// Code generated by protoc-gen-go. DO NOT EDIT.
// source: position_report.proto

package positionreport

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResponseStatus int32

const (
	ResponseStatus_OK    ResponseStatus = 0
	ResponseStatus_ERROR ResponseStatus = 1
)

var ResponseStatus_name = map[int32]string{
	0: "OK",
	1: "ERROR",
}

var ResponseStatus_value = map[string]int32{
	"OK":    0,
	"ERROR": 1,
}

func (x ResponseStatus) String() string {
	return proto.EnumName(ResponseStatus_name, int32(x))
}

func (ResponseStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3e9efea65861b64e, []int{0}
}

type PositionUpdate struct {
	SequenceNumber       *SequenceNumber `protobuf:"bytes,1,opt,name=sequenceNumber,proto3" json:"sequenceNumber,omitempty"`
	Position             *Position       `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	RobotId              *RobotId        `protobuf:"bytes,3,opt,name=robotId,proto3" json:"robotId,omitempty"`
	SessionId            *SessionId      `protobuf:"bytes,4,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PositionUpdate) Reset()         { *m = PositionUpdate{} }
func (m *PositionUpdate) String() string { return proto.CompactTextString(m) }
func (*PositionUpdate) ProtoMessage()    {}
func (*PositionUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e9efea65861b64e, []int{0}
}

func (m *PositionUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PositionUpdate.Unmarshal(m, b)
}
func (m *PositionUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PositionUpdate.Marshal(b, m, deterministic)
}
func (m *PositionUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PositionUpdate.Merge(m, src)
}
func (m *PositionUpdate) XXX_Size() int {
	return xxx_messageInfo_PositionUpdate.Size(m)
}
func (m *PositionUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_PositionUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_PositionUpdate proto.InternalMessageInfo

func (m *PositionUpdate) GetSequenceNumber() *SequenceNumber {
	if m != nil {
		return m.SequenceNumber
	}
	return nil
}

func (m *PositionUpdate) GetPosition() *Position {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *PositionUpdate) GetRobotId() *RobotId {
	if m != nil {
		return m.RobotId
	}
	return nil
}

func (m *PositionUpdate) GetSessionId() *SessionId {
	if m != nil {
		return m.SessionId
	}
	return nil
}

type PeportResponse struct {
	ResponseStatus       ResponseStatus `protobuf:"varint,1,opt,name=responseStatus,proto3,enum=positionreport.ResponseStatus" json:"responseStatus,omitempty"`
	StatusMessage        string         `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PeportResponse) Reset()         { *m = PeportResponse{} }
func (m *PeportResponse) String() string { return proto.CompactTextString(m) }
func (*PeportResponse) ProtoMessage()    {}
func (*PeportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e9efea65861b64e, []int{1}
}

func (m *PeportResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeportResponse.Unmarshal(m, b)
}
func (m *PeportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeportResponse.Marshal(b, m, deterministic)
}
func (m *PeportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeportResponse.Merge(m, src)
}
func (m *PeportResponse) XXX_Size() int {
	return xxx_messageInfo_PeportResponse.Size(m)
}
func (m *PeportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PeportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PeportResponse proto.InternalMessageInfo

func (m *PeportResponse) GetResponseStatus() ResponseStatus {
	if m != nil {
		return m.ResponseStatus
	}
	return ResponseStatus_OK
}

func (m *PeportResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

type SequenceNumber struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SequenceNumber) Reset()         { *m = SequenceNumber{} }
func (m *SequenceNumber) String() string { return proto.CompactTextString(m) }
func (*SequenceNumber) ProtoMessage()    {}
func (*SequenceNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e9efea65861b64e, []int{2}
}

func (m *SequenceNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SequenceNumber.Unmarshal(m, b)
}
func (m *SequenceNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SequenceNumber.Marshal(b, m, deterministic)
}
func (m *SequenceNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SequenceNumber.Merge(m, src)
}
func (m *SequenceNumber) XXX_Size() int {
	return xxx_messageInfo_SequenceNumber.Size(m)
}
func (m *SequenceNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_SequenceNumber.DiscardUnknown(m)
}

var xxx_messageInfo_SequenceNumber proto.InternalMessageInfo

func (m *SequenceNumber) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Position struct {
	X                    int32    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e9efea65861b64e, []int{3}
}

func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Position) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type RobotId struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RobotId) Reset()         { *m = RobotId{} }
func (m *RobotId) String() string { return proto.CompactTextString(m) }
func (*RobotId) ProtoMessage()    {}
func (*RobotId) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e9efea65861b64e, []int{4}
}

func (m *RobotId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RobotId.Unmarshal(m, b)
}
func (m *RobotId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RobotId.Marshal(b, m, deterministic)
}
func (m *RobotId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RobotId.Merge(m, src)
}
func (m *RobotId) XXX_Size() int {
	return xxx_messageInfo_RobotId.Size(m)
}
func (m *RobotId) XXX_DiscardUnknown() {
	xxx_messageInfo_RobotId.DiscardUnknown(m)
}

var xxx_messageInfo_RobotId proto.InternalMessageInfo

func (m *RobotId) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type SessionId struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionId) Reset()         { *m = SessionId{} }
func (m *SessionId) String() string { return proto.CompactTextString(m) }
func (*SessionId) ProtoMessage()    {}
func (*SessionId) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e9efea65861b64e, []int{5}
}

func (m *SessionId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionId.Unmarshal(m, b)
}
func (m *SessionId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionId.Marshal(b, m, deterministic)
}
func (m *SessionId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionId.Merge(m, src)
}
func (m *SessionId) XXX_Size() int {
	return xxx_messageInfo_SessionId.Size(m)
}
func (m *SessionId) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionId.DiscardUnknown(m)
}

var xxx_messageInfo_SessionId proto.InternalMessageInfo

func (m *SessionId) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterEnum("positionreport.ResponseStatus", ResponseStatus_name, ResponseStatus_value)
	proto.RegisterType((*PositionUpdate)(nil), "positionreport.PositionUpdate")
	proto.RegisterType((*PeportResponse)(nil), "positionreport.PeportResponse")
	proto.RegisterType((*SequenceNumber)(nil), "positionreport.SequenceNumber")
	proto.RegisterType((*Position)(nil), "positionreport.Position")
	proto.RegisterType((*RobotId)(nil), "positionreport.RobotId")
	proto.RegisterType((*SessionId)(nil), "positionreport.SessionId")
}

func init() { proto.RegisterFile("position_report.proto", fileDescriptor_3e9efea65861b64e) }

var fileDescriptor_3e9efea65861b64e = []byte{
	// 400 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0xdf, 0x8b, 0xd3, 0x40,
	0x10, 0xbe, 0xcd, 0x99, 0xbb, 0xcb, 0xa8, 0xcb, 0xb1, 0x2a, 0xe6, 0x14, 0x8a, 0x44, 0x29, 0x45,
	0x30, 0xc1, 0x2a, 0xf8, 0x28, 0x14, 0x14, 0x8a, 0x68, 0xc3, 0x54, 0xc5, 0x37, 0xc9, 0x8f, 0x35,
	0x46, 0x68, 0x36, 0xee, 0x6e, 0x68, 0xfb, 0xe2, 0x1f, 0xee, 0x93, 0x64, 0x93, 0xb4, 0x6c, 0x8a,
	0x6f, 0xb3, 0x33, 0xdf, 0x37, 0x3b, 0xdf, 0xb7, 0xb3, 0xf0, 0xa0, 0x16, 0xaa, 0xd4, 0xa5, 0xa8,
	0xbe, 0x4b, 0x5e, 0x0b, 0xa9, 0xc3, 0x5a, 0x0a, 0x2d, 0x18, 0x1d, 0xd2, 0x5d, 0x36, 0xf8, 0x4b,
	0x80, 0xc6, 0x7d, 0xea, 0x4b, 0x9d, 0x27, 0x9a, 0xb3, 0xf7, 0x40, 0x15, 0xff, 0xdd, 0xf0, 0x2a,
	0xe3, 0x9f, 0x9a, 0x4d, 0xca, 0xa5, 0x4f, 0x9e, 0x90, 0xd9, 0xed, 0xf9, 0x24, 0xb4, 0xb9, 0xe1,
	0xda, 0x42, 0xe1, 0x88, 0xc5, 0x5e, 0xc3, 0xd5, 0x40, 0xf0, 0x1d, 0xd3, 0xc1, 0x1f, 0x77, 0x18,
	0x6e, 0xc6, 0x03, 0x92, 0xbd, 0x84, 0x4b, 0x29, 0x52, 0xa1, 0x97, 0xb9, 0x7f, 0x6e, 0x48, 0x0f,
	0xc7, 0x24, 0xec, 0xca, 0x38, 0xe0, 0xd8, 0x1b, 0xf0, 0x14, 0x57, 0xaa, 0x14, 0xd5, 0x32, 0xf7,
	0x6f, 0x19, 0xd2, 0xcd, 0xe9, 0xac, 0x3d, 0x00, 0x8f, 0xd8, 0xe0, 0x0f, 0xd0, 0xd8, 0x94, 0x91,
	0xab, 0x5a, 0x54, 0xca, 0x68, 0x97, 0x7d, 0xbc, 0xd6, 0x89, 0x6e, 0x94, 0xd1, 0x4e, 0x4f, 0xb5,
	0xa3, 0x85, 0xc2, 0x11, 0x8b, 0x3d, 0x83, 0xbb, 0xca, 0x44, 0x1f, 0xb9, 0x52, 0x49, 0xc1, 0x8d,
	0x01, 0x1e, 0xda, 0xc9, 0x60, 0x0a, 0xd4, 0xf6, 0x90, 0xdd, 0x07, 0x37, 0x13, 0x4d, 0xa5, 0xcd,
	0xb5, 0xe7, 0xd8, 0x1d, 0x82, 0x29, 0x5c, 0x0d, 0x4e, 0xb1, 0x3b, 0x40, 0x76, 0xa6, 0xea, 0x22,
	0xd9, 0xb5, 0xa7, 0xbd, 0xe9, 0xed, 0x22, 0xd9, 0x07, 0x37, 0x70, 0xd9, 0x9b, 0xc3, 0x28, 0x38,
	0x65, 0xde, 0xe3, 0x9c, 0x32, 0x0f, 0x1e, 0x83, 0x77, 0xb0, 0x60, 0x5c, 0x7c, 0xfe, 0x14, 0xa8,
	0xad, 0x87, 0x5d, 0x80, 0xb3, 0xfa, 0x70, 0x7d, 0xc6, 0x3c, 0x70, 0xdf, 0x21, 0xae, 0xf0, 0x9a,
	0xcc, 0x7f, 0x1c, 0x17, 0x05, 0x8d, 0x07, 0xec, 0x73, 0x4b, 0x6b, 0xa3, 0xc3, 0x70, 0x93, 0xff,
	0x3d, 0x70, 0xb7, 0x5a, 0x8f, 0x4e, 0xeb, 0x96, 0xfd, 0xc1, 0xd9, 0x8c, 0x2c, 0xbe, 0xc1, 0xdb,
	0xa2, 0xd4, 0x3f, 0x9b, 0x34, 0xcc, 0xc4, 0x26, 0xca, 0x79, 0xf5, 0x4b, 0x54, 0x2a, 0x6a, 0x75,
	0x7d, 0x2d, 0xf9, 0x96, 0xcb, 0xc8, 0x3c, 0xfb, 0x8b, 0x22, 0xd1, 0x7c, 0x9b, 0xec, 0xa3, 0x42,
	0xd6, 0x59, 0x64, 0x77, 0x5d, 0xdc, 0xb3, 0x07, 0x8d, 0xdb, 0xcd, 0x8f, 0x49, 0x7a, 0x61, 0xbe,
	0xc0, 0xab, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x76, 0x62, 0x75, 0x8a, 0x1b, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PositionReportClient is the client API for PositionReport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PositionReportClient interface {
	ReportPosition(ctx context.Context, opts ...grpc.CallOption) (PositionReport_ReportPositionClient, error)
}

type positionReportClient struct {
	cc grpc.ClientConnInterface
}

func NewPositionReportClient(cc grpc.ClientConnInterface) PositionReportClient {
	return &positionReportClient{cc}
}

func (c *positionReportClient) ReportPosition(ctx context.Context, opts ...grpc.CallOption) (PositionReport_ReportPositionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PositionReport_serviceDesc.Streams[0], "/positionreport.PositionReport/ReportPosition", opts...)
	if err != nil {
		return nil, err
	}
	x := &positionReportReportPositionClient{stream}
	return x, nil
}

type PositionReport_ReportPositionClient interface {
	Send(*PositionUpdate) error
	CloseAndRecv() (*PeportResponse, error)
	grpc.ClientStream
}

type positionReportReportPositionClient struct {
	grpc.ClientStream
}

func (x *positionReportReportPositionClient) Send(m *PositionUpdate) error {
	return x.ClientStream.SendMsg(m)
}

func (x *positionReportReportPositionClient) CloseAndRecv() (*PeportResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(PeportResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PositionReportServer is the server API for PositionReport service.
type PositionReportServer interface {
	ReportPosition(PositionReport_ReportPositionServer) error
}

// UnimplementedPositionReportServer can be embedded to have forward compatible implementations.
type UnimplementedPositionReportServer struct {
}

func (*UnimplementedPositionReportServer) ReportPosition(srv PositionReport_ReportPositionServer) error {
	return status.Errorf(codes.Unimplemented, "method ReportPosition not implemented")
}

func RegisterPositionReportServer(s *grpc.Server, srv PositionReportServer) {
	s.RegisterService(&_PositionReport_serviceDesc, srv)
}

func _PositionReport_ReportPosition_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PositionReportServer).ReportPosition(&positionReportReportPositionServer{stream})
}

type PositionReport_ReportPositionServer interface {
	SendAndClose(*PeportResponse) error
	Recv() (*PositionUpdate, error)
	grpc.ServerStream
}

type positionReportReportPositionServer struct {
	grpc.ServerStream
}

func (x *positionReportReportPositionServer) SendAndClose(m *PeportResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *positionReportReportPositionServer) Recv() (*PositionUpdate, error) {
	m := new(PositionUpdate)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _PositionReport_serviceDesc = grpc.ServiceDesc{
	ServiceName: "positionreport.PositionReport",
	HandlerType: (*PositionReportServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReportPosition",
			Handler:       _PositionReport_ReportPosition_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "position_report.proto",
}
