// Code generated by protoc-gen-go. DO NOT EDIT.
// source: position_report.proto

package positionreport

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SessionState int32

const (
	SessionState_STARTED  SessionState = 0
	SessionState_FINISHED SessionState = 1
)

var SessionState_name = map[int32]string{
	0: "STARTED",
	1: "FINISHED",
}

var SessionState_value = map[string]int32{
	"STARTED":  0,
	"FINISHED": 1,
}

func (x SessionState) String() string {
	return proto.EnumName(SessionState_name, int32(x))
}

func (SessionState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3e9efea65861b64e, []int{0}
}

type ResponseStatus int32

const (
	ResponseStatus_OK    ResponseStatus = 0
	ResponseStatus_ERROR ResponseStatus = 1
)

var ResponseStatus_name = map[int32]string{
	0: "OK",
	1: "ERROR",
}

var ResponseStatus_value = map[string]int32{
	"OK":    0,
	"ERROR": 1,
}

func (x ResponseStatus) String() string {
	return proto.EnumName(ResponseStatus_name, int32(x))
}

func (ResponseStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3e9efea65861b64e, []int{1}
}

type SessionUpdate struct {
	SessionId            *SessionId   `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	SessionState         SessionState `protobuf:"varint,2,opt,name=sessionState,proto3,enum=positionreport.SessionState" json:"sessionState,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SessionUpdate) Reset()         { *m = SessionUpdate{} }
func (m *SessionUpdate) String() string { return proto.CompactTextString(m) }
func (*SessionUpdate) ProtoMessage()    {}
func (*SessionUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e9efea65861b64e, []int{0}
}

func (m *SessionUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionUpdate.Unmarshal(m, b)
}
func (m *SessionUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionUpdate.Marshal(b, m, deterministic)
}
func (m *SessionUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionUpdate.Merge(m, src)
}
func (m *SessionUpdate) XXX_Size() int {
	return xxx_messageInfo_SessionUpdate.Size(m)
}
func (m *SessionUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_SessionUpdate proto.InternalMessageInfo

func (m *SessionUpdate) GetSessionId() *SessionId {
	if m != nil {
		return m.SessionId
	}
	return nil
}

func (m *SessionUpdate) GetSessionState() SessionState {
	if m != nil {
		return m.SessionState
	}
	return SessionState_STARTED
}

type SessionUpdateResponse struct {
	ResponseStatus       ResponseStatus `protobuf:"varint,1,opt,name=responseStatus,proto3,enum=positionreport.ResponseStatus" json:"responseStatus,omitempty"`
	StatusMessage        string         `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SessionUpdateResponse) Reset()         { *m = SessionUpdateResponse{} }
func (m *SessionUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*SessionUpdateResponse) ProtoMessage()    {}
func (*SessionUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e9efea65861b64e, []int{1}
}

func (m *SessionUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionUpdateResponse.Unmarshal(m, b)
}
func (m *SessionUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionUpdateResponse.Marshal(b, m, deterministic)
}
func (m *SessionUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionUpdateResponse.Merge(m, src)
}
func (m *SessionUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_SessionUpdateResponse.Size(m)
}
func (m *SessionUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SessionUpdateResponse proto.InternalMessageInfo

func (m *SessionUpdateResponse) GetResponseStatus() ResponseStatus {
	if m != nil {
		return m.ResponseStatus
	}
	return ResponseStatus_OK
}

func (m *SessionUpdateResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

type PositionUpdate struct {
	SequenceNumber       *SequenceNumber `protobuf:"bytes,1,opt,name=sequenceNumber,proto3" json:"sequenceNumber,omitempty"`
	Position             *Position       `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	RobotId              *RobotId        `protobuf:"bytes,3,opt,name=robotId,proto3" json:"robotId,omitempty"`
	SessionId            *SessionId      `protobuf:"bytes,4,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PositionUpdate) Reset()         { *m = PositionUpdate{} }
func (m *PositionUpdate) String() string { return proto.CompactTextString(m) }
func (*PositionUpdate) ProtoMessage()    {}
func (*PositionUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e9efea65861b64e, []int{2}
}

func (m *PositionUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PositionUpdate.Unmarshal(m, b)
}
func (m *PositionUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PositionUpdate.Marshal(b, m, deterministic)
}
func (m *PositionUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PositionUpdate.Merge(m, src)
}
func (m *PositionUpdate) XXX_Size() int {
	return xxx_messageInfo_PositionUpdate.Size(m)
}
func (m *PositionUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_PositionUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_PositionUpdate proto.InternalMessageInfo

func (m *PositionUpdate) GetSequenceNumber() *SequenceNumber {
	if m != nil {
		return m.SequenceNumber
	}
	return nil
}

func (m *PositionUpdate) GetPosition() *Position {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *PositionUpdate) GetRobotId() *RobotId {
	if m != nil {
		return m.RobotId
	}
	return nil
}

func (m *PositionUpdate) GetSessionId() *SessionId {
	if m != nil {
		return m.SessionId
	}
	return nil
}

type PositionUpdateResponse struct {
	ResponseStatus       ResponseStatus `protobuf:"varint,1,opt,name=responseStatus,proto3,enum=positionreport.ResponseStatus" json:"responseStatus,omitempty"`
	StatusMessage        string         `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PositionUpdateResponse) Reset()         { *m = PositionUpdateResponse{} }
func (m *PositionUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*PositionUpdateResponse) ProtoMessage()    {}
func (*PositionUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e9efea65861b64e, []int{3}
}

func (m *PositionUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PositionUpdateResponse.Unmarshal(m, b)
}
func (m *PositionUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PositionUpdateResponse.Marshal(b, m, deterministic)
}
func (m *PositionUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PositionUpdateResponse.Merge(m, src)
}
func (m *PositionUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_PositionUpdateResponse.Size(m)
}
func (m *PositionUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PositionUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PositionUpdateResponse proto.InternalMessageInfo

func (m *PositionUpdateResponse) GetResponseStatus() ResponseStatus {
	if m != nil {
		return m.ResponseStatus
	}
	return ResponseStatus_OK
}

func (m *PositionUpdateResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

type SequenceNumber struct {
	Value                int64    `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SequenceNumber) Reset()         { *m = SequenceNumber{} }
func (m *SequenceNumber) String() string { return proto.CompactTextString(m) }
func (*SequenceNumber) ProtoMessage()    {}
func (*SequenceNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e9efea65861b64e, []int{4}
}

func (m *SequenceNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SequenceNumber.Unmarshal(m, b)
}
func (m *SequenceNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SequenceNumber.Marshal(b, m, deterministic)
}
func (m *SequenceNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SequenceNumber.Merge(m, src)
}
func (m *SequenceNumber) XXX_Size() int {
	return xxx_messageInfo_SequenceNumber.Size(m)
}
func (m *SequenceNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_SequenceNumber.DiscardUnknown(m)
}

var xxx_messageInfo_SequenceNumber proto.InternalMessageInfo

func (m *SequenceNumber) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Position struct {
	X                    int32    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e9efea65861b64e, []int{5}
}

func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Position) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type RobotId struct {
	Value                string   `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RobotId) Reset()         { *m = RobotId{} }
func (m *RobotId) String() string { return proto.CompactTextString(m) }
func (*RobotId) ProtoMessage()    {}
func (*RobotId) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e9efea65861b64e, []int{6}
}

func (m *RobotId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RobotId.Unmarshal(m, b)
}
func (m *RobotId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RobotId.Marshal(b, m, deterministic)
}
func (m *RobotId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RobotId.Merge(m, src)
}
func (m *RobotId) XXX_Size() int {
	return xxx_messageInfo_RobotId.Size(m)
}
func (m *RobotId) XXX_DiscardUnknown() {
	xxx_messageInfo_RobotId.DiscardUnknown(m)
}

var xxx_messageInfo_RobotId proto.InternalMessageInfo

func (m *RobotId) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type SessionId struct {
	Value                string   `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionId) Reset()         { *m = SessionId{} }
func (m *SessionId) String() string { return proto.CompactTextString(m) }
func (*SessionId) ProtoMessage()    {}
func (*SessionId) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e9efea65861b64e, []int{7}
}

func (m *SessionId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionId.Unmarshal(m, b)
}
func (m *SessionId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionId.Marshal(b, m, deterministic)
}
func (m *SessionId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionId.Merge(m, src)
}
func (m *SessionId) XXX_Size() int {
	return xxx_messageInfo_SessionId.Size(m)
}
func (m *SessionId) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionId.DiscardUnknown(m)
}

var xxx_messageInfo_SessionId proto.InternalMessageInfo

func (m *SessionId) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterEnum("positionreport.SessionState", SessionState_name, SessionState_value)
	proto.RegisterEnum("positionreport.ResponseStatus", ResponseStatus_name, ResponseStatus_value)
	proto.RegisterType((*SessionUpdate)(nil), "positionreport.SessionUpdate")
	proto.RegisterType((*SessionUpdateResponse)(nil), "positionreport.SessionUpdateResponse")
	proto.RegisterType((*PositionUpdate)(nil), "positionreport.PositionUpdate")
	proto.RegisterType((*PositionUpdateResponse)(nil), "positionreport.PositionUpdateResponse")
	proto.RegisterType((*SequenceNumber)(nil), "positionreport.SequenceNumber")
	proto.RegisterType((*Position)(nil), "positionreport.Position")
	proto.RegisterType((*RobotId)(nil), "positionreport.RobotId")
	proto.RegisterType((*SessionId)(nil), "positionreport.SessionId")
}

func init() { proto.RegisterFile("position_report.proto", fileDescriptor_3e9efea65861b64e) }

var fileDescriptor_3e9efea65861b64e = []byte{
	// 502 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x54, 0x51, 0x6f, 0xd3, 0x30,
	0x10, 0xae, 0x37, 0xba, 0x36, 0xd7, 0x36, 0xaa, 0x0c, 0x83, 0x82, 0xa0, 0x8c, 0x00, 0x55, 0x99,
	0x44, 0x23, 0x02, 0x12, 0x8f, 0xc0, 0xb4, 0x56, 0x54, 0x88, 0xad, 0xba, 0x8c, 0xc1, 0x03, 0x12,
	0x4a, 0x5b, 0xab, 0x04, 0xb1, 0x38, 0xc4, 0x8e, 0xb6, 0xfe, 0x00, 0x78, 0xe0, 0x8f, 0xf1, 0x9f,
	0x78, 0x42, 0x71, 0xe2, 0xae, 0xee, 0xe8, 0xc4, 0x1b, 0x6f, 0xf6, 0xdd, 0xf7, 0x7d, 0xbe, 0xfb,
	0xee, 0x64, 0xd8, 0x8e, 0xb9, 0x08, 0x65, 0xc8, 0xa3, 0x4f, 0x09, 0x8b, 0x79, 0x22, 0x7b, 0x71,
	0xc2, 0x25, 0xa7, 0xb6, 0x0e, 0xe7, 0x51, 0xe7, 0x27, 0x81, 0x86, 0xcf, 0x84, 0x08, 0x79, 0xf4,
	0x2e, 0x9e, 0x06, 0x92, 0xd1, 0xe7, 0x60, 0x89, 0x3c, 0x30, 0x9c, 0xb6, 0xc8, 0x0e, 0xe9, 0xd6,
	0xbc, 0x9b, 0x3d, 0x93, 0xd5, 0xf3, 0x35, 0x00, 0xcf, 0xb1, 0xf4, 0x25, 0xd4, 0x8b, 0x8b, 0x2f,
	0x03, 0xc9, 0x5a, 0x1b, 0x3b, 0xa4, 0x6b, 0x7b, 0xb7, 0xd7, 0x70, 0x15, 0x06, 0x0d, 0x86, 0xf3,
	0x9d, 0xc0, 0xb6, 0x51, 0x0c, 0x32, 0x11, 0xf3, 0x48, 0x30, 0x3a, 0x00, 0x3b, 0x29, 0xce, 0x19,
	0x34, 0x15, 0xaa, 0x32, 0xdb, 0x6b, 0xaf, 0xaa, 0xa3, 0x81, 0xc2, 0x15, 0x16, 0x7d, 0x00, 0x0d,
	0xa1, 0x4e, 0x6f, 0x99, 0x10, 0xc1, 0x2c, 0x2f, 0xd2, 0x42, 0x33, 0xe8, 0xfc, 0x26, 0x60, 0x8f,
	0x0a, 0xdd, 0xc2, 0x95, 0x01, 0xd8, 0x82, 0x7d, 0x4b, 0x59, 0x34, 0x61, 0x07, 0xe9, 0xc9, 0x98,
	0x25, 0x85, 0x35, 0xed, 0x8b, 0xed, 0x2d, 0xa3, 0x70, 0x85, 0x45, 0x9f, 0x41, 0x55, 0x13, 0xd4,
	0xdb, 0x35, 0xaf, 0xb5, 0xaa, 0xa0, 0x5f, 0xc6, 0x05, 0x92, 0x3e, 0x81, 0x4a, 0xc2, 0xc7, 0x5c,
	0x0e, 0xa7, 0xad, 0x4d, 0x45, 0xba, 0x71, 0xa1, 0xef, 0x3c, 0x8d, 0x1a, 0x67, 0x8e, 0xf1, 0xca,
	0xbf, 0x8f, 0xd1, 0xf9, 0x41, 0xe0, 0xba, 0xd9, 0xfc, 0x7f, 0x9a, 0x42, 0x07, 0x6c, 0xd3, 0x4c,
	0x7a, 0x0d, 0xca, 0xc7, 0xc1, 0xd7, 0x94, 0xa9, 0x67, 0x37, 0x31, 0xbf, 0x38, 0x1d, 0xa8, 0xea,
	0x7a, 0x69, 0x1d, 0xc8, 0x99, 0xca, 0x96, 0x91, 0x9c, 0x65, 0xb7, 0xb9, 0xd2, 0x2e, 0x23, 0x99,
	0x3b, 0x77, 0xa1, 0x52, 0xb8, 0x64, 0x0a, 0x59, 0x5a, 0xe8, 0x1e, 0x58, 0x0b, 0x47, 0xfe, 0x0e,
	0xd9, 0x7d, 0x04, 0xf5, 0xe5, 0xfd, 0xa5, 0x35, 0xa8, 0xf8, 0x47, 0xaf, 0xf0, 0xa8, 0xbf, 0xdf,
	0x2c, 0xd1, 0x3a, 0x54, 0x07, 0xc3, 0x83, 0xa1, 0xff, 0xba, 0xbf, 0xdf, 0x24, 0xbb, 0xf7, 0xc1,
	0x36, 0x6d, 0xa0, 0x5b, 0xb0, 0x71, 0xf8, 0xa6, 0x59, 0xa2, 0x16, 0x94, 0xfb, 0x88, 0x87, 0xd8,
	0x24, 0xde, 0xaf, 0xa5, 0x4d, 0x43, 0xe5, 0x1d, 0xfd, 0x98, 0xf1, 0xb2, 0xd3, 0xa2, 0xa9, 0xf6,
	0xba, 0x0d, 0xc9, 0xc7, 0x73, 0xab, 0x73, 0x79, 0x5e, 0x57, 0xe1, 0x94, 0xba, 0x84, 0xbe, 0x87,
	0x46, 0xae, 0x5e, 0xb4, 0x41, 0xef, 0xac, 0x59, 0x8a, 0x42, 0xfb, 0xe1, 0xa5, 0xe9, 0x73, 0xe9,
	0xbd, 0x0f, 0xf0, 0x62, 0x16, 0xca, 0xcf, 0xe9, 0xb8, 0x37, 0xe1, 0x27, 0xee, 0x94, 0x45, 0x5f,
	0x78, 0x24, 0xdc, 0xcc, 0xf0, 0xe3, 0x90, 0x9d, 0xb2, 0xc4, 0x55, 0x8b, 0xf9, 0x78, 0x16, 0x48,
	0x76, 0x1a, 0xcc, 0xdd, 0x59, 0x12, 0x4f, 0x5c, 0x53, 0x7a, 0xef, 0xaa, 0xe9, 0xc4, 0x28, 0xfb,
	0xb0, 0x46, 0x64, 0xbc, 0xa5, 0x7e, 0xae, 0xa7, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xfe, 0xf7,
	0xb0, 0x07, 0xd2, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PositionReportClient is the client API for PositionReport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PositionReportClient interface {
	ReportPosition(ctx context.Context, opts ...grpc.CallOption) (PositionReport_ReportPositionClient, error)
	ReportSession(ctx context.Context, in *SessionUpdate, opts ...grpc.CallOption) (*SessionUpdateResponse, error)
}

type positionReportClient struct {
	cc grpc.ClientConnInterface
}

func NewPositionReportClient(cc grpc.ClientConnInterface) PositionReportClient {
	return &positionReportClient{cc}
}

func (c *positionReportClient) ReportPosition(ctx context.Context, opts ...grpc.CallOption) (PositionReport_ReportPositionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PositionReport_serviceDesc.Streams[0], "/positionreport.PositionReport/ReportPosition", opts...)
	if err != nil {
		return nil, err
	}
	x := &positionReportReportPositionClient{stream}
	return x, nil
}

type PositionReport_ReportPositionClient interface {
	Send(*PositionUpdate) error
	CloseAndRecv() (*PositionUpdateResponse, error)
	grpc.ClientStream
}

type positionReportReportPositionClient struct {
	grpc.ClientStream
}

func (x *positionReportReportPositionClient) Send(m *PositionUpdate) error {
	return x.ClientStream.SendMsg(m)
}

func (x *positionReportReportPositionClient) CloseAndRecv() (*PositionUpdateResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(PositionUpdateResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *positionReportClient) ReportSession(ctx context.Context, in *SessionUpdate, opts ...grpc.CallOption) (*SessionUpdateResponse, error) {
	out := new(SessionUpdateResponse)
	err := c.cc.Invoke(ctx, "/positionreport.PositionReport/ReportSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PositionReportServer is the server API for PositionReport service.
type PositionReportServer interface {
	ReportPosition(PositionReport_ReportPositionServer) error
	ReportSession(context.Context, *SessionUpdate) (*SessionUpdateResponse, error)
}

// UnimplementedPositionReportServer can be embedded to have forward compatible implementations.
type UnimplementedPositionReportServer struct {
}

func (*UnimplementedPositionReportServer) ReportPosition(srv PositionReport_ReportPositionServer) error {
	return status.Errorf(codes.Unimplemented, "method ReportPosition not implemented")
}
func (*UnimplementedPositionReportServer) ReportSession(ctx context.Context, req *SessionUpdate) (*SessionUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportSession not implemented")
}

func RegisterPositionReportServer(s *grpc.Server, srv PositionReportServer) {
	s.RegisterService(&_PositionReport_serviceDesc, srv)
}

func _PositionReport_ReportPosition_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PositionReportServer).ReportPosition(&positionReportReportPositionServer{stream})
}

type PositionReport_ReportPositionServer interface {
	SendAndClose(*PositionUpdateResponse) error
	Recv() (*PositionUpdate, error)
	grpc.ServerStream
}

type positionReportReportPositionServer struct {
	grpc.ServerStream
}

func (x *positionReportReportPositionServer) SendAndClose(m *PositionUpdateResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *positionReportReportPositionServer) Recv() (*PositionUpdate, error) {
	m := new(PositionUpdate)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PositionReport_ReportSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionReportServer).ReportSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/positionreport.PositionReport/ReportSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionReportServer).ReportSession(ctx, req.(*SessionUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

var _PositionReport_serviceDesc = grpc.ServiceDesc{
	ServiceName: "positionreport.PositionReport",
	HandlerType: (*PositionReportServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportSession",
			Handler:    _PositionReport_ReportSession_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReportPosition",
			Handler:       _PositionReport_ReportPosition_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "position_report.proto",
}
