CREATE TABLE Floors (
  id SERIAL PRIMARY KEY,
  uuid VARCHAR(36) UNIQUE NOT NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  name VARCHAR(100) NOT NULL,
  width INTEGER NOT NULL,
  grid INTEGER[] NOT NULL
);

CREATE TABLE Robots (
  id SERIAL PRIMARY KEY,
  uuid VARCHAR(36) UNIQUE NOT NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  name VARCHAR(100) NOT NULL,
  width INTEGER NOT NULL,
  grid INTEGER[] NOT NULL,
  floorId bigint REFERENCES Floors(id)
);

CREATE UNIQUE INDEX floor_id_index ON Floors (uuid);

CREATE UNIQUE INDEX robot_id_index ON Robots (uuid);